# This workflow will do a release after merge to develop branch

name: Relese Tao extension

on:
  push

jobs:
  auto-release:
    name: Automated Tao extension release
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Release
      uses: oat-sa/extension-release-action@9998416746dd4f8397b9552b9955f1d49b4e4b45
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.BUILD_NPM_TOKEN }}
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        npm_token: ${{ secrets.BUILD_NPM_TOKEN }}
