# This workflow will do a release after merge to develop branch

name: Relese Tao extension

on:
  pull_request:
    branches:
      - develop
    types: [closed]
jobs:
  auto-release:
    if: github.event.pull_request.merged == true
    name: Automated Tao extension release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Release
      uses: oat-sa/extension-release-action@3cda2820a98c595221da48adcbc42e0e2dcc721c
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        github_token: ${{ secrets.GH_TOKEN }}
